#!/usr/bin/env bash
if test ! -z $LUCAS_MONTENEGRO_ROOT_DIR; then
  echo "
CLI already running. Bye!
"
else
  export LUCAS_MONTENEGRO_ROOT_DIR=$(pwd)
  export PATH=$LUCAS_MONTENEGRO_ROOT_DIR/scripts:$PATH
  source SetEnvLib
  SetEnv development
  bold=$(tput bold)
  green=$(tput setaf 10)
  reset=$(tput sgr0)
  export PS1="$PS1\\[$bold${green}\\]lmcli\\[$reset\\]> "
  echo "
      $bold$green┌───────────────────────────────────────────────────────┐$reset
      $bold$green│$reset                                                       $bold$green│$reset
      $bold$green│$reset                                                       $bold$green│$reset
      $bold$green│$reset                 Lucas Montenegro CLI                  $bold$green│$reset
      $bold$green│$reset  https://github.com/lucasMontenegro/lucas-montenegro  $bold$green│$reset
      $bold$green│$reset                                                       $bold$green│$reset
      $bold$green│$reset                                                       $bold$green│$reset
      $bold$green└───────────────────────────────────────────────────────┘$reset
  "
fi
