#!/bin/sh
if test -z $LUCAS_MONTENEGRO_ROOT_DIR; then
  echo "
Not running inside the lmcli. Bye!
"
  exit 1
fi
cd $LUCAS_MONTENEGRO_ROOT_DIR
case "$1" in
  assets)
    npx serve
    ;;
  api)
    node server
    ;;
  *)
    echo "
Usage: Serve <assets|api>
"
esac
