#!/bin/sh
if test -z "$LUCAS_MONTENEGRO_ROOT_DIR"; then
  echo "
Not running inside the lmcli. Bye!
"
elif ! ( test ! -z "$1" && expr match "$1" "production\|development" 1>/dev/null ) ; then
  echo "
Usage: source SetEnv <production|development>
"
else
  cwd=$(pwd)
  cd $LUCAS_MONTENEGRO_ROOT_DIR/env
  . ./defaults.sh
  . ./$1-defaults.sh
  test -f ./locals.sh && . ./locals.sh
  test -f ./$1-locals.sh && . ./$1-locals.sh
  cd $cwd
fi
